### ISSUE TITLE
Pre-Commit compatibillity issue with PYTHONPATH

### ISSUE THREAD

**Issue by niall-byrne** [jshwi/docsig#522]
I'm seeing some behaviour that I wanted to make sure I was identifying correctly.
This is specifically in relation to the `--check-overidden` option.

There appears to be a **variance** between the CLI usage and when using the pre-commit hook.

This example will pass CLI checks, but will fail a pre-commit run:

pyproject.toml

```toml
[tool.docsig]
check-class_constructor = true
check-dunders = false
check-overridden = false
check-protected = false
```

folder/bases/base_class.py

```python
class BaseClass:
  """My base class."""

  def method(self, arg) -> None:
    """Does something.

    :param arg: some argument
    """
    return None
```

folder/implementation1.py

```python

from .bases.base_class import BaseClass

class Implementation(BaseClass):
  """My implementation."""

  def method(self, arg) -> None:
    """Does something."""
    return None
```

I can run:
```docsig folder/implementation1.py```

This is no problem.

```pre-commit run docsig --all-files```

This fails.

After playing around with this a bit, it seems relative imports are the problem.
If I instead change this to a fully qualified import path, it will work consistently.

So this led me to trying:

```PYTHONPATH=$PWD pre-commit run docsig --all-files```

Which works fine.
I am hesitant to suggest a change at this point, as I haven't looked at the codebase yet.
Do you have any hunches as to how this might be mitigated?

Environment:

- Python version: Python 3.9.16
- docsig version: 0.65.0

**Comment by niall-byrne** [comment]
I can sort of mitigate it with:

```yaml
  - repo: https://github.com/jshwi/docsig
    rev: v0.65.0
    hooks:
      - id: docsig
        entry: bash -c 'PYTHONPATH=$PWD docsig $@'
```

**Comment by jshwi** [comment]
Hi @niall-byrne 

Thanks for opening this issue

I am actually aware of this issue, when I came across this the first time it took me a while to work it out, sorry if took you a bit of time too

The inference for check overridden is provided by `pylint`'s `astoid`, and is explained in the following `pylint` documentation: https://pylint.pycqa.org/en/stable/user_guide/installation/pre-commit-integration.html

I use it like the following, and therefore am unable to use it with `pre-commit`'s CI, and so have to use it with my `github` actions

```yaml
# $ cat .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      # local so package can be imported to lint
      - id: lint
        name: lint
        entry: make .make/lint
        language: system
        pass_filenames: false
```
```makefile
# $ cat Makefile
#: lint code
.make/lint: $(VENV) $(PYTHON_FILES)
	@$(POETRY) run pylint --output-format=colorized $(PYTHON_FILES)
	@$(POETRY) run docsig $(PYTHON_FILES)
	@mkdir -p $(@D)
	@touch $@
```

The main issue, I think, is poor documentation and `--check-overidden` won't work when using the hook provided in this package for the `pre-commit` package manager

As, unlike with `pylint`, `asteroid` is not essential for the majority of this package I thought maybe a warning would help, or an error when using `--check-overidden` with `pre-commit`, but I never got round to it. What do you think?

Cheers,
Stephen
